// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tnawmausqduqtpvvmszl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYXdtYXVzcWR1cXRwdnZtc3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTcwNjcsImV4cCI6MjA3MjIzMzA2N30.JUQ9NqZWA5C1T7Va2NMhDs_G04vESdZDCi1UJFX_n7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);